## There are 5 different terrain types defined in this project -- mesh, box, stairs, slopes, random.
#
## For "mesh" terrain, the grid size, mesh location and heightmap file name need to be specified.
## For "box" terrain, the box size(l,w,h) and box location need to be specified.
## For "stairs" terrain, the number of stair steps, step height, step depth, stair width and stair location need to be specified.
## For "slopes" terrain, the slope degrees, slope width, slope length and slope location need to be specified.
## For "random" terrain, the area range of it, the size range of obstacles and terrain location need to be specified.
#
## In addition, more complicated terrain can be created by combining above 5 basic terrain elements.
## For example, Stair-bridge can be built by using box and 2 stairs, and Slope-bridge can be founded by using box and 2 slopes.

ground-plane:
    type: "infinite-plane"
    mu: 0.5
    restitution: 0.0
    #height: -0.5
    height: 0.0
    graphicsSize: [20,20] # how large the plane appears
    checkers: [40,40]     # how many checkers are on the plane
    
    
#box-22:
    type: "box"
    mu: 0.7
    restitution: 0
    depth: 1
    width: 1.2
    height: 0.5
    #position:  [1.5, 0, 0.025]
    position: [2.32, 0.0, 0.0]
    orientation: [0, 0.0, 0] # roll pitch yaw
    transparent: 0
 

  
#stairs-21:
    type: "stairs"
    steps: 5
    rise: .05
    run: .25
    width: 1.2
    mu: .7
    restitution: 0
  #position: [0.5, 0, -0.52]
    position: [0.3, 0, 0.0]
    orientation: [0, 0, 0]
    transparent: 0
