// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.0

#ifndef _PredictionMsg_h
#define _PredictionMsg_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _PredictionMsg PredictionMsg;
struct _PredictionMsg
{
    double     leg_1_pred;
    double     leg_2_pred;
    double     leg_3_pred;
    double     leg_4_pred;
};

/**
 * Create a deep copy of a PredictionMsg.
 * When no longer needed, destroy it with PredictionMsg_destroy()
 */
PredictionMsg* PredictionMsg_copy(const PredictionMsg* to_copy);

/**
 * Destroy an instance of PredictionMsg created by PredictionMsg_copy()
 */
void PredictionMsg_destroy(PredictionMsg* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _PredictionMsg_subscription_t PredictionMsg_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * PredictionMsg is received.
 */
typedef void(*PredictionMsg_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const PredictionMsg *msg, void *userdata);

/**
 * Publish a message of type PredictionMsg using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int PredictionMsg_publish(lcm_t *lcm, const char *channel, const PredictionMsg *msg);

/**
 * Subscribe to messages of type PredictionMsg using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
PredictionMsg_subscription_t* PredictionMsg_subscribe(
    lcm_t *lcm, const char *channel, PredictionMsg_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by PredictionMsg_subscribe()
 */
int PredictionMsg_unsubscribe(lcm_t *lcm, PredictionMsg_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int PredictionMsg_subscription_set_queue_capacity(
    PredictionMsg_subscription_t* subs, int num_messages);

/**
 * Encode a message of type PredictionMsg into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to PredictionMsg_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int PredictionMsg_encode(void *buf, int offset, int maxlen, const PredictionMsg *p);

/**
 * Decode a message of type PredictionMsg from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with PredictionMsg_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int PredictionMsg_decode(const void *buf, int offset, int maxlen, PredictionMsg *msg);

/**
 * Release resources allocated by PredictionMsg_decode()
 * @return 0
 */
int PredictionMsg_decode_cleanup(PredictionMsg *p);

/**
 * Check how many bytes are required to encode a message of type PredictionMsg
 */
int PredictionMsg_encoded_size(const PredictionMsg *p);

// LCM support functions. Users should not call these
int64_t __PredictionMsg_get_hash(void);
uint64_t __PredictionMsg_hash_recursive(const __lcm_hash_ptr *p);
int __PredictionMsg_encode_array(
    void *buf, int offset, int maxlen, const PredictionMsg *p, int elements);
int __PredictionMsg_decode_array(
    const void *buf, int offset, int maxlen, PredictionMsg *p, int elements);
int __PredictionMsg_decode_array_cleanup(PredictionMsg *p, int elements);
int __PredictionMsg_encoded_array_size(const PredictionMsg *p, int elements);
int __PredictionMsg_clone_array(const PredictionMsg *p, PredictionMsg *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
