// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.0

#include <string.h>
#include "PredictionMsg.h"

static int __PredictionMsg_hash_computed;
static uint64_t __PredictionMsg_hash;

uint64_t __PredictionMsg_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __PredictionMsg_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __PredictionMsg_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x7bb6e67b060ce325LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __PredictionMsg_get_hash(void)
{
    if (!__PredictionMsg_hash_computed) {
        __PredictionMsg_hash = (int64_t)__PredictionMsg_hash_recursive(NULL);
        __PredictionMsg_hash_computed = 1;
    }

    return __PredictionMsg_hash;
}

int __PredictionMsg_encode_array(void *buf, int offset, int maxlen, const PredictionMsg *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].leg_1_pred), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].leg_2_pred), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].leg_3_pred), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].leg_4_pred), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int PredictionMsg_encode(void *buf, int offset, int maxlen, const PredictionMsg *p)
{
    int pos = 0, thislen;
    int64_t hash = __PredictionMsg_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __PredictionMsg_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __PredictionMsg_encoded_array_size(const PredictionMsg *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __double_encoded_array_size(&(p[element].leg_1_pred), 1);

        size += __double_encoded_array_size(&(p[element].leg_2_pred), 1);

        size += __double_encoded_array_size(&(p[element].leg_3_pred), 1);

        size += __double_encoded_array_size(&(p[element].leg_4_pred), 1);

    }
    return size;
}

int PredictionMsg_encoded_size(const PredictionMsg *p)
{
    return 8 + __PredictionMsg_encoded_array_size(p, 1);
}

int __PredictionMsg_decode_array(const void *buf, int offset, int maxlen, PredictionMsg *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].leg_1_pred), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].leg_2_pred), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].leg_3_pred), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].leg_4_pred), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __PredictionMsg_decode_array_cleanup(PredictionMsg *p, int elements)
{
    (void)p;
    int element;
    for (element = 0; element < elements; element++) {

        __double_decode_array_cleanup(&(p[element].leg_1_pred), 1);

        __double_decode_array_cleanup(&(p[element].leg_2_pred), 1);

        __double_decode_array_cleanup(&(p[element].leg_3_pred), 1);

        __double_decode_array_cleanup(&(p[element].leg_4_pred), 1);

    }
    return 0;
}

int PredictionMsg_decode(const void *buf, int offset, int maxlen, PredictionMsg *p)
{
    int pos = 0, thislen;
    int64_t hash = __PredictionMsg_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __PredictionMsg_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int PredictionMsg_decode_cleanup(PredictionMsg *p)
{
    return __PredictionMsg_decode_array_cleanup(p, 1);
}

int __PredictionMsg_clone_array(const PredictionMsg *p, PredictionMsg *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_clone_array(&(p[element].leg_1_pred), &(q[element].leg_1_pred), 1);

        __double_clone_array(&(p[element].leg_2_pred), &(q[element].leg_2_pred), 1);

        __double_clone_array(&(p[element].leg_3_pred), &(q[element].leg_3_pred), 1);

        __double_clone_array(&(p[element].leg_4_pred), &(q[element].leg_4_pred), 1);

    }
    return 0;
}

PredictionMsg *PredictionMsg_copy(const PredictionMsg *p)
{
    PredictionMsg *q = (PredictionMsg*) malloc(sizeof(PredictionMsg));
    __PredictionMsg_clone_array(p, q, 1);
    return q;
}

void PredictionMsg_destroy(PredictionMsg *p)
{
    __PredictionMsg_decode_array_cleanup(p, 1);
    free(p);
}

int PredictionMsg_publish(lcm_t *lc, const char *channel, const PredictionMsg *p)
{
      int max_data_size = PredictionMsg_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = PredictionMsg_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _PredictionMsg_subscription_t {
    PredictionMsg_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void PredictionMsg_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    PredictionMsg p;
    memset(&p, 0, sizeof(PredictionMsg));
    status = PredictionMsg_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding PredictionMsg!!!\n", status);
        return;
    }

    PredictionMsg_subscription_t *h = (PredictionMsg_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    PredictionMsg_decode_cleanup (&p);
}

PredictionMsg_subscription_t* PredictionMsg_subscribe (lcm_t *lcm,
                    const char *channel,
                    PredictionMsg_handler_t f, void *userdata)
{
    PredictionMsg_subscription_t *n = (PredictionMsg_subscription_t*)
                       malloc(sizeof(PredictionMsg_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 PredictionMsg_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg PredictionMsg LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int PredictionMsg_subscription_set_queue_capacity (PredictionMsg_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int PredictionMsg_unsubscribe(lcm_t *lcm, PredictionMsg_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe PredictionMsg_handler %p!\n", (void*)hid);
        return -1;
    }
    free (hid);
    return 0;
}

